#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
        listen [::]:80 default_server;
	    
	    root /var/www/html;
	        index index.html index.htm index.nginx-debian.html;
		    
		    server_name _;
		        
		        location / {
			        try_files \$uri \$uri/ =404;
				    }
			    }
			    EOF'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
