#!/usr/bin/env bash
#Install nginx web server
apt-get -y update
apt-get -y install nginx
echo "Hello world!" > /var/www/html/index.html

# Start nginx (without using systemctl)
/usr/sbin/nginx
service nginx start