#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when 
#+   receiving a SIGQUIT or SIGTERM signal

pid=$$
pid_file="/var/run/myscript.pid"

echo "$pid" > "$pid_file"
terminator() {
  rm "$pid_file"
  exit
}

#Displays To infinity and beyond indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && terminator' SIGTERM
    trap 'terminator' SIGQUITgit
done