#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving 
#   a SIGQUIT or SIGTERM signal

pid = $$
pid_file = "/var/run/myscript.pid"

echo "$pid" > "$pid_file"

#Displays To infinity and beyond indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
    trap echo ' "I hate the kill command" && terminate' SIGTERM
    trap echo ' "Y U no love me?!"; exit' SIGINT
    trap echo ' rm "$pid_file"; exit' SIGQUIT SIGTERM
done